apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tic_toc_toe
  description: Playback Order
  tags:
    - react
    - game
  annotations:
    github.com/project-slug: aishwaryajoshsoftware/tic_toc_toe
spec:
  type: service
  lifecycle: production
  owner: user:guest
  system: audio-playback
